### ISSUE TITLE
No access : telnet and Snap.cgi

### ISSUE THREAD

**Issue by kwetnico** [guino/Merkury1080P#17] opened 2021-11-01 17:26 UTC
Hello, I hacked my camera: (hardwareversion ":" M16S_A2_V10_F37 "," firmwareversion ":" ppstrong-a3-tuya2_lsc-4.0.6.20210311 ")
![image](https://user-images.githubusercontent.com/55591810/139714055-de89ee2b-6b1e-4b2c-8ba7-e7d614d528be.png)

**The rtsp stream is working fine thanks.**
I wanted to test telnet and live access to snap.cgi but it doesn't work: I have access denied for snapshot and telnet ..
I modified the http.conf file (without the hash) and passwd (with the hash).
I even added the line not to ask for a password but impossible (custom.sh) and the hardware is ok :
![1](https://user-images.githubusercontent.com/55591810/139713494-4cb3180d-a5c2-47f1-9d79-a9f008e735e1.png)

What can I do to make it work ? Thank you

my http.conf :
![2](https://user-images.githubusercontent.com/55591810/139713508-ee193d38-6c67-4e9a-8a56-eca9cbf8b5a5.jpg)

my passwd :
![3](https://user-images.githubusercontent.com/55591810/139713519-ca4f8edf-ae84-43d4-9425-e2af7ac32469.jpg)

**Comment by guino** [comment] 2021-11-01 17:39
@kwetnico this is a duplicate of https://github.com/guino/BazzDoorbell/issues/58 and I have answered it on that link.

**Closed** 2021-11-01 17:42 UTC
